/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formulario;

import Datos.AlumnoDAO;
import Datos.AsistenciaDAO;
import Datos.HabilidadDAO;
import Entidad.Alumno;
import Entidad.Asistencia;
import Entidad.Habilidad;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author estrosebas
 */
public class AsistenciaMenu extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private static final String DIRECTORIO_MATRICULAS = "C:\\matriculas";
    private static final String ARCHIVO_SESION = DIRECTORIO_MATRICULAS + "\\sesion.txt"; // Ruta al archivo de configuración
    ImageIcon iconoPersonalizado = new ImageIcon(login.class.getResource("/cheque.png"));
    ImageIcon iconoPersonalizadoAlerta = new ImageIcon(login.class.getResource("/alerta.png"));
//ImageIcon iconoPersonalizado = new ImageIcon(getImage(getClass().getResource("/beca.png"));
    public AsistenciaMenu() {
        initComponents();
        setLocationRelativeTo(null);
        
    }
    public Image getIconImage() {
        //Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("/beca.png"));
        Image retValue = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/beca.png"));

        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        RegistrarAlumnos = new javax.swing.JButton();
        modificarAlumno = new javax.swing.JButton();
        EliminarAlumno = new javax.swing.JButton();
        regreasr = new javax.swing.JButton();
        dnientrada = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);

        jPanel6.setBackground(new java.awt.Color(252, 241, 225));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Dni", "Fecha", "Temprano/Tarde"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 615, 265));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Asistencia");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0, 100));

        RegistrarAlumnos.setText("Registrar");
        RegistrarAlumnos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                RegistrarAlumnosMouseMoved(evt);
            }
        });
        RegistrarAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegistrarAlumnosMouseExited(evt);
            }
        });
        RegistrarAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarAlumnosActionPerformed(evt);
            }
        });

        modificarAlumno.setText("Modificar");
        modificarAlumno.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                modificarAlumnoMouseMoved(evt);
            }
        });
        modificarAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modificarAlumnoMouseExited(evt);
            }
        });
        modificarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarAlumnoActionPerformed(evt);
            }
        });

        EliminarAlumno.setText("Eliminar");
        EliminarAlumno.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                EliminarAlumnoMouseMoved(evt);
            }
        });
        EliminarAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EliminarAlumnoMouseExited(evt);
            }
        });
        EliminarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarAlumnoActionPerformed(evt);
            }
        });

        regreasr.setText("Regresar");
        regreasr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regreasrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(RegistrarAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modificarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EliminarAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(225, 225, 225)
                .addComponent(regreasr)
                .addGap(18, 18, 18))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrarAlumnos)
                    .addComponent(modificarAlumno)
                    .addComponent(EliminarAlumno)
                    .addComponent(regreasr)))
        );

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 610, 40));

        dnientrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dnientradaActionPerformed(evt);
            }
        });
        jPanel6.add(dnientrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 140, -1));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("DNI :");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        jButton1.setText("Buscar");
        jButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton1MouseMoved(evt);
            }
        });
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backe.jpg"))); // NOI18N
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarAlumnosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarAlumnosMouseMoved

        RegistrarAlumnos.setBackground(new Color(0, 128, 128));
    }//GEN-LAST:event_RegistrarAlumnosMouseMoved

    private void RegistrarAlumnosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarAlumnosMouseExited
        RegistrarAlumnos.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_RegistrarAlumnosMouseExited

    private void RegistrarAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarAlumnosActionPerformed
        lectorQR registrar = new lectorQR();
        registrar.setVisible(true);
    }//GEN-LAST:event_RegistrarAlumnosActionPerformed

    private void modificarAlumnoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarAlumnoMouseMoved
        modificarAlumno.setBackground(new Color(0, 128, 128));
    }//GEN-LAST:event_modificarAlumnoMouseMoved

    private void modificarAlumnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarAlumnoMouseExited
        modificarAlumno.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_modificarAlumnoMouseExited

    private void modificarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarAlumnoActionPerformed
        modificarAsistencia frame = new modificarAsistencia();
        frame.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_modificarAlumnoActionPerformed

    private void EliminarAlumnoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarAlumnoMouseMoved
        EliminarAlumno.setBackground(new Color(0, 128, 128));
    }//GEN-LAST:event_EliminarAlumnoMouseMoved

    private void EliminarAlumnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarAlumnoMouseExited
        EliminarAlumno.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_EliminarAlumnoMouseExited

    private void EliminarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarAlumnoActionPerformed
        eliminarAlumno frame = new eliminarAlumno();
        frame.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_EliminarAlumnoActionPerformed

    private void jButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseMoved
        jButton1.setBackground(new Color(0, 128, 128));
    }//GEN-LAST:event_jButton1MouseMoved

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //consultaralumnos();
        //JOptionPane.showMessageDialog(null, "Actualizado!");

        //
        try {
            consultar();
        } catch (Exception e) {
            e.printStackTrace();
        }
        JOptionPane.showMessageDialog(null, "Actualizado!");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void dnientradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dnientradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dnientradaActionPerformed

    private void regreasrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regreasrActionPerformed
        login frame = new login();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_regreasrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsistenciaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsistenciaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsistenciaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsistenciaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsistenciaMenu().setVisible(true);
            }
        });
    }
    void consultar() {
        AsistenciaDAO asistenciaDAO = new AsistenciaDAO();

        // Obtener la lista de todas las habilidades
        List<Asistencia> listaAsistencia = asistenciaDAO.obtenerAsistenciaPorDNI(Integer.parseInt(dnientrada.getText()));

        // Limpia las filas existentes en la tabla
        DefaultTableModel modelo = (DefaultTableModel) Tabla.getModel();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }

        // Iterar sobre la lista de habilidades y agregarlas a la tabla
        for (Asistencia asistencia : listaAsistencia) {
            Object[] filaHabilidad = new Object[]{
                asistencia.getId_asistencia(),
                asistencia.getDni(),
                asistencia.getFecha_hora(),
                asistencia.getLlegada_temprano()
            };
            modelo.addRow(filaHabilidad);
        }

        Tabla.setModel(modelo);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EliminarAlumno;
    private javax.swing.JButton RegistrarAlumnos;
    private javax.swing.JTable Tabla;
    private javax.swing.JTextField dnientrada;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificarAlumno;
    private javax.swing.JButton regreasr;
    // End of variables declaration//GEN-END:variables
}
