/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formulario;

/**
 *
 * @author estrosebas
 */
import Entidad.Representante;
import Datos.RepresentanteDAO;
import javax.swing.JOptionPane;

public class buscarRepresentante extends javax.swing.JFrame {

    /**
     * Creates new form modificarAlumno
     */
    public buscarRepresentante() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        buscarDni = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        nom_Repre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ape_PRe = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ape_MRe = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        id_distritoR = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        sexo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        domicilio = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        lugar_traba = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        correo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        id_telefono = new javax.swing.JTextField();
        ocupacion = new javax.swing.JTextField();
        id_Repre = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(10, 10, 10, 100));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ingrese el dni:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 59, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Buscar representante");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 16, -1, 22));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 10));

        buscarDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarDniActionPerformed(evt);
            }
        });
        jPanel2.add(buscarDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 56, 101, -1));

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jPanel2.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 56, -1, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 91, 300, 10));

        jLabel4.setText("Nombre :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 110, -1, -1));

        nom_Repre.setEditable(false);
        nom_Repre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_RepreActionPerformed(evt);
            }
        });
        jPanel2.add(nom_Repre, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 107, 214, -1));

        jLabel5.setText("Apellido Paterno :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 138, -1, -1));

        ape_PRe.setEditable(false);
        jPanel2.add(ape_PRe, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 135, 170, -1));

        jLabel6.setText("Apelllido Materno :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 166, -1, -1));

        ape_MRe.setEditable(false);
        jPanel2.add(ape_MRe, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 163, 163, -1));

        jLabel8.setText("ID Distrito :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 194, -1, -1));

        id_distritoR.setEditable(false);
        jPanel2.add(id_distritoR, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 191, 206, -1));

        jLabel9.setText("Sexo :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 222, -1, -1));

        sexo.setEditable(false);
        jPanel2.add(sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 219, 233, -1));

        jLabel10.setText("Domicilio :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 247, -1, -1));

        jLabel11.setText("Ocupacion :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 275, -1, -1));

        domicilio.setEditable(false);
        jPanel2.add(domicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 244, 207, -1));

        jLabel12.setText("Lugar de trabajo :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 303, -1, -1));

        lugar_traba.setEditable(false);
        jPanel2.add(lugar_traba, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 300, 172, -1));

        jLabel13.setText("Correo :");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 331, -1, -1));

        correo.setEditable(false);
        jPanel2.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 328, 222, -1));

        jLabel14.setText("id telefono :");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 359, -1, -1));

        id_telefono.setEditable(false);
        jPanel2.add(id_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 356, 201, -1));

        ocupacion.setEditable(false);
        jPanel2.add(ocupacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 272, 200, -1));

        id_Repre.setEditable(false);
        id_Repre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_RepreActionPerformed(evt);
            }
        });
        jPanel2.add(id_Repre, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 0, 34, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 300, 390));

        back.setText("Regresar");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backe.jpg"))); // NOI18N
        jLabel1.setText("r");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 440));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        //menuunitario back = new menuunitario();
        //back.setVisible(true);
        this.setVisible(false); // Oculta el JFrame actual
    }//GEN-LAST:event_backActionPerformed
    // Método que maneja la búsqueda de un alumno

    private void buscar() {
        try {
            int dni = Integer.parseInt(buscarDni.getText()); // Asegúrate de manejar NumberFormatException
            RepresentanteDAO repDAO = new RepresentanteDAO();
            Representante representante = repDAO.buscarRepresentantePorDni(dni);
            if (representante != null) {
                // Rellenar los campos con la información del representante
                nom_Repre.setText(representante.getNom_Repre());
                ape_PRe.setText(representante.getApe_PRe());
                ape_MRe.setText(representante.getApe_MRe());
                sexo.setText(representante.getSexo());
                id_distritoR.setText(Integer.toString(representante.getId_distritoR()));
                domicilio.setText(representante.getDomicilio());
                ocupacion.setText(representante.getOcupacion());
                lugar_traba.setText(representante.getLugar_traba());
                correo.setText(representante.getCorreo());
                id_telefono.setText(Integer.toString(representante.getId_telefono()));
                id_Repre.setText(Integer.toString(representante.getId_Repre()));
            } else {
                JOptionPane.showMessageDialog(this, "Representante no encontrado", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un DNI válido.", "Error de formato", JOptionPane.ERROR_MESSAGE);
        }
    }


    private void buscarDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarDniActionPerformed

    }//GEN-LAST:event_buscarDniActionPerformed

    private void nom_RepreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_RepreActionPerformed

    }//GEN-LAST:event_nom_RepreActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        buscar();
    }//GEN-LAST:event_buscarActionPerformed

    private void id_RepreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_RepreActionPerformed

    }//GEN-LAST:event_id_RepreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buscarRepresentante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buscarRepresentante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buscarRepresentante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buscarRepresentante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buscarRepresentante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ape_MRe;
    private javax.swing.JTextField ape_PRe;
    private javax.swing.JButton back;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField buscarDni;
    private javax.swing.JTextField correo;
    private javax.swing.JTextField domicilio;
    private javax.swing.JTextField id_Repre;
    private javax.swing.JTextField id_distritoR;
    private javax.swing.JTextField id_telefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField lugar_traba;
    private javax.swing.JTextField nom_Repre;
    private javax.swing.JTextField ocupacion;
    private javax.swing.JTextField sexo;
    // End of variables declaration//GEN-END:variables
}
