/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formulario;

/**
 *
 * @author estrosebas
 */
import Entidad.Alumno;
import Datos.AlumnoDAO;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

public class buscarAlumno extends javax.swing.JFrame {

    /**
     * Creates new form modificarAlumno
     */
    public buscarAlumno() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        buscarDni = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        nom_Alu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ape_PAl = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ape_MAl = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fec_Nac = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        id_distritoAlum = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        sexo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        domicilio = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        grado_ing = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        colegio_ant = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        id_habilidad = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        id_Repre = new javax.swing.JTextField();
        relacion = new javax.swing.JTextField();
        nivel_ing = new javax.swing.JTextField();
        id_Alumno = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(10, 10, 10, 100));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ingrese el dni:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 59, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Buscar alumno");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 16, -1, 22));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 300, 10));

        buscarDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarDniActionPerformed(evt);
            }
        });
        jPanel2.add(buscarDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 56, 101, -1));

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jPanel2.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 56, -1, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 91, 300, 10));

        jLabel4.setText("Nombre :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 110, -1, -1));

        nom_Alu.setEditable(false);
        nom_Alu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_AluActionPerformed(evt);
            }
        });
        jPanel2.add(nom_Alu, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 107, 202, -1));

        jLabel5.setText("Apellido Paterno :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 138, -1, -1));

        ape_PAl.setEditable(false);
        jPanel2.add(ape_PAl, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 135, 158, -1));

        jLabel6.setText("Apelllido Materno :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 166, -1, -1));

        ape_MAl.setEditable(false);
        jPanel2.add(ape_MAl, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 163, 151, -1));

        jLabel7.setText("Fecha de nacimiento :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 194, -1, -1));

        fec_Nac.setEditable(false);
        jPanel2.add(fec_Nac, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 191, 136, -1));

        jLabel8.setText("ID Distrito :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 222, -1, -1));

        id_distritoAlum.setEditable(false);
        jPanel2.add(id_distritoAlum, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 219, 194, -1));

        jLabel9.setText("Sexo :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 250, -1, -1));

        sexo.setEditable(false);
        jPanel2.add(sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 247, 221, -1));

        jLabel10.setText("Domicilio :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 278, -1, -1));

        jLabel11.setText("Nivel ingreso :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 303, -1, -1));

        domicilio.setEditable(false);
        jPanel2.add(domicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 275, 195, -1));

        jLabel12.setText("Grado ingreso :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 331, -1, -1));

        grado_ing.setEditable(false);
        jPanel2.add(grado_ing, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 328, 172, -1));

        jLabel13.setText("Colegio Anterior :");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 359, -1, -1));

        colegio_ant.setEditable(false);
        jPanel2.add(colegio_ant, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 356, 159, -1));

        jLabel14.setText("Id_habilidad :");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 387, -1, -1));

        id_habilidad.setEditable(false);
        jPanel2.add(id_habilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 384, 182, -1));

        jLabel16.setText("ID Representante :");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 415, -1, -1));

        jLabel17.setText("Realcion :");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 443, -1, -1));

        id_Repre.setEditable(false);
        jPanel2.add(id_Repre, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 412, 157, -1));

        relacion.setEditable(false);
        jPanel2.add(relacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 440, 201, -1));

        nivel_ing.setEditable(false);
        jPanel2.add(nivel_ing, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 300, 171, -1));

        id_Alumno.setEditable(false);
        id_Alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_AlumnoActionPerformed(evt);
            }
        });
        jPanel2.add(id_Alumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 0, 34, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 300, 480));

        back.setText("Regresar");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backe vertical.jpg"))); // NOI18N
        jLabel1.setText("r");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 530));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        
        //menuunitario back = new menuunitario();
        //back.setVisible(true);
        this.setVisible(false); // Oculta el JFrame actual
    }//GEN-LAST:event_backActionPerformed
    // Método que maneja la búsqueda de un alumno

    private void buscar() {
        try {
            int dni = Integer.parseInt(buscarDni.getText()); // Asegúrate de manejar NumberFormatException
            AlumnoDAO aluDAO = new AlumnoDAO();
            Alumno alumno = new Alumno();
            alumno = aluDAO.buscarAlumnoPorDni(dni);
            if (alumno != null) {
                // Rellenar los campos con la información del alumno
                nom_Alu.setText(alumno.getNom_Alu());
                ape_PAl.setText(alumno.getApe_PAl());
                ape_MAl.setText(alumno.getApe_MAl());
                //parsear la fecha a string para el textfield
                SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");

                Date fec = alumno.getFec_Nac();
                String Fec_Nac = formato.format(fec);
                fec_Nac.setText(Fec_Nac);

                /////fin parseo y seteo
                id_distritoAlum.setText(Integer.toString(alumno.getId_distritoAlum()));
                sexo.setText(alumno.getSexo());
                domicilio.setText(alumno.getDomicilio());
                nivel_ing.setText(alumno.getNivel_ing());
                grado_ing.setText(Integer.toString(alumno.getGrado_ing()));
                colegio_ant.setText(alumno.getColegio_ant());
                id_habilidad.setText(Integer.toString(alumno.getId_habilidad()));
                id_Repre.setText(Integer.toString(alumno.getId_Repre()));
                relacion.setText(alumno.getRelacion());
                id_Alumno.setText(Integer.toString(alumno.getId_Alumno()));
            } else {
                JOptionPane.showMessageDialog(this, "Alumno no encontrado", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un DNI válido.", "Error de formato", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void buscarDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarDniActionPerformed
        
    }//GEN-LAST:event_buscarDniActionPerformed

    private void nom_AluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_AluActionPerformed
        
    }//GEN-LAST:event_nom_AluActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        buscar();
    }//GEN-LAST:event_buscarActionPerformed

    private void id_AlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_AlumnoActionPerformed
       
    }//GEN-LAST:event_id_AlumnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buscarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buscarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buscarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buscarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buscarAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ape_MAl;
    private javax.swing.JTextField ape_PAl;
    private javax.swing.JButton back;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField buscarDni;
    private javax.swing.JTextField colegio_ant;
    private javax.swing.JTextField domicilio;
    private javax.swing.JTextField fec_Nac;
    private javax.swing.JTextField grado_ing;
    private javax.swing.JTextField id_Alumno;
    private javax.swing.JTextField id_Repre;
    private javax.swing.JTextField id_distritoAlum;
    private javax.swing.JTextField id_habilidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField nivel_ing;
    private javax.swing.JTextField nom_Alu;
    private javax.swing.JTextField relacion;
    private javax.swing.JTextField sexo;
    // End of variables declaration//GEN-END:variables
}
